<?php

namespace CoreBundle\Repository;

/**
 * DemandeContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeContactRepository extends \Doctrine\ORM\EntityRepository
{
}
